import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <header className="sticky top-0 z-10 border-b bg-white/80 dark:bg-black/60 backdrop-blur">
          <nav className="mx-auto max-w-5xl px-4 py-3 flex items-center gap-4 text-sm">
            <Link href="/" className="font-semibold">Home</Link>
            <Link href="/read" className="hover:underline">Read</Link>
            <Link href="/comparison" className="hover:underline">Comparison</Link>
            <Link href="/summary" className="hover:underline">Summary</Link>
            <Link href="/bibliography" className="hover:underline">Bibliography</Link>
          </nav>
        </header>
        <main className="mx-auto max-w-5xl px-4 py-6">
          {children}
        </main>
      </body>
    </html>
  );
}
